# This is a TOML document

# "single" or "multiple", multiple mode needs SSL certificate
mode = "single"

[server]
close_delay = 500
# Use intranet for "single" mode, and extranet for "multiple" mode
host = "localhost"
port = 3000

# DON'T USE THIS IN PRODUCTION, GENERATE YOUR OWN KEYS
[vapid]
email = "noreply@example.com"
private_key = "Ib8rbVH2uksPrFfD0aQlldDgB7AvOLo9xiOhvUCVcNo"
public_key = "BJ8at-_GOJDfUBClVFGri12TD3OBpFyuc3O_8E1tgTts0oahPOceg3n8Y9-OS0eeigNhm2D7FzdhedO2f3b0Ljs"